CREATE TABLE USR_main ( 
	ID 							UUID 					DEFAULT gen_random_uuid(), 
	EMAIL 					VARCHAR(255) 	NOT NULL,
	PASSWORD_TOKEN 			VARCHAR(300) 	NOT NULL,
	VERIFIED 				BOOLEAN 		NOT NULL	DEFAULT FALSE,
	PERSON 					UUID,
	DATE_CREATED 			TIMESTAMP		NOT NULL	DEFAULT NOW(),
	DATE_MODIFIED 			TIMESTAMP 		NOT NULL	DEFAULT NOW(),
	CONSTRAINT PK_USER_MAIN PRIMARY KEY (ID),
	CONSTRAINT UQ_USER_EMAIL UNIQUE(EMAIL)
);


