CREATE TABLE USR_metadata (
	ID				UUID							DEFAULT gen_random_uuid(),
	KEY				VARCHAR(255)	NOT NULL,
	VALUE			TEXT,
	USER_ID			UUID			NOT NULL,
	DATE_CREATED 	TIMESTAMP		NOT NULL 		DEFAULT NOW(),
	DATE_MODIFIED	TIMESTAMP		NOT NULL		DEFAULT NOW(),
	CONSTRAINT PK_USER_METADATA PRIMARY KEY (ID),
	CONSTRAINT FK_USER_METADATA FOREIGN KEY(USER_ID) REFERENCES USR_main(ID)
);